events {}
http {
  server {
    listen 80;

    # Forward UI traffic to Vite WITHOUT stripping the path
    location /token-exchange/ {
      proxy_pass http://frontend:5173;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "Upgrade";
      proxy_set_header Host $host;
    }

    # Forward API traffic to Backend (and strip the /api prefix)
    location /api/ {
      proxy_pass http://backend:3001/;
    }
  }
}